# Generated by Django 2.2.10 on 2020-02-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdata',
            name='timestamp',
            field=models.BigIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='Timestamp'),
        ),
    ]
